首先，我们导入 PyTorch。

In [ ]:
import torch # 导入 PyTorch 库

/opt/anaconda3/envs/py310/lib/python3.10/site-packages/torch/_subclasses/functional_tensor.py:275: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:81.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


让我们看一些基本的张量操作。首先，介绍几种创建张量的方法：

In [ ]:
z = torch.zeros(5, 3) # 创建一个 5x3 的全零张量
print(z)
print(z.dtype) # 打印张量的数据类型

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


上面，我们创建了一个 5x3 的填充零的矩阵，并查询了它的数据类型，发现这些零是 32 位浮点数，这是 PyTorch 的默认设置。

如果你想要整数怎么办？你可以随时覆盖默认设置：

In [ ]:
i = torch.ones((5, 3), dtype=torch.int16) # 创建一个 5x3 的全一张量，数据类型为 16 位整数
print(i)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)


你可以看到，当我们更改默认设置时，张量在打印时会清晰地报告这一点。

通常会随机初始化学习权重，通常使用特定的 PRNG（伪随机数生成器）种子以确保结果的可重复性：

In [ ]:
torch.manual_seed(1729) # 设置随机种子以确保可重复性
r1 = torch.rand(2, 2) # 创建一个 2x2 的随机张量
print('一个随机张量:')
print(r1)

r2 = torch.rand(2, 2) # 创建另一个 2x2 的随机张量
print('\n另一个不同的随机张量:')
print(r2) # 新的值

torch.manual_seed(1729) # 重新设置相同的随机种子
r3 = torch.rand(2, 2) # 再次创建随机张量
print('\n应该与 r1 匹配:')
print(r3) # 由于重新设置种子，重复 r1 的值

A random tensor:
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])

A different random tensor:
tensor([[0.4216, 0.0691],
        [0.2332, 0.4047]])

Should match r1:
tensor([[0.3126, 0.3791],
        [0.3087, 0.0736]])


PyTorch 张量直观地执行算术运算。形状相似的张量可以进行加法、乘法等运算。与标量的运算会分布到张量的每个元素上：

In [ ]:
ones = torch.ones(2, 3) # 创建一个 2x3 的全一张量
print(ones)

twos = torch.ones(2, 3) * 2 # 每个元素乘以 2
print(twos)

threes = ones + twos       # 允许加法，因为形状相似
print(threes)              # 张量按元素相加
print(threes.shape)        # 结果张量与输入张量具有相同的维度

r1 = torch.rand(2, 3) # 创建一个 2x3 的随机张量
r2 = torch.rand(3, 2) # 创建一个 3x2 的随机张量
# r3 = r1 + r2 # 这行会报错，因为形状不匹配无法进行元素级加法

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.]])
tensor([[3., 3., 3.],
        [3., 3., 3.]])
torch.Size([2, 3])


RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

以下是可用数学运算的一小部分示例：

In [ ]:
r = torch.rand(2, 2) - 0.5 * 2 # 创建一个值在 -1 和 1 之间的 2x2 随机张量
print('一个随机矩阵, r:')
print(r)

# 支持常见的数学运算:
print('\nr 的绝对值:')
print(torch.abs(r)) # 计算绝对值

# ...以及三角函数:
print('\nr 的反正弦:')
print(torch.asin(r)) # 计算反正弦

# ...以及线性代数运算，如行列式和奇异值分解
print('\nr 的行列式:')
print(torch.det(r)) # 计算行列式
print('\nr 的奇异值分解:')
print(torch.svd(r)) # 计算奇异值分解

# ...以及统计和聚合运算:
print('\nr 的平均值和标准差:')
print(torch.std_mean(r)) # 计算标准差和均值
print('\nr 的最大值:')
print(torch.max(r)) # 计算最大值

A random matrix, r:
tensor([[-0.0022, -0.6116],
        [-0.3071, -0.8297]])

Absolute value of r:
tensor([[0.0022, 0.6116],
        [0.3071, 0.8297]])

Inverse sine of r:
tensor([[-0.0022, -0.6581],
        [-0.3122, -0.9785]])

Determinant of r:
tensor(-0.1860)

Singular value decomposition of r:
torch.return_types.svd(
U=tensor([[-0.5599, -0.8286],
        [-0.8286,  0.5599]]),
S=tensor([1.0611, 0.1753]),
V=tensor([[ 0.2410, -0.9705],
        [ 0.9705,  0.2410]]))

Average and standard deviation of r:
(tensor(0.3608), tensor(-0.4376))

Maximum value of r:
tensor(-0.0022)


关于 PyTorch 张量的强大功能还有很多需要了解，包括如何设置它们以在 GPU 上进行并行计算——我们将在另一个视频中更深入地探讨。